version: '3.9'
services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    platform: linux/x86_64
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5

  backend:
    container_name: app_backend
    build: ./backend
    ports: 
      - 4001:4001
    platform: linux/x86_64
    working_dir: /app_backend
    command: npm run dev
    volumes: 
      - ./backend/src:/app_backend/src
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_PORT=4001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=database
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5

  database:
    image: mysql:8.0.21
    container_name: database
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
